server:
  port: 8888

wechat:
  miniapp:
    appId: wxe92819f5cdd4ba7a
    appSecret: 2f8475a39dcd8f0de4a0e9e48af8768f
    templateId: RyPDvws09dmfmLUmPUq9XaYuu3tp_ph1MvX_8U4Yn8U
    templatePage: /pages/report/report